MySchedulerWork/Models/Program_Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MySchedulerWork.Models
{
    public class Program_Subject
    {
        public int Id { get; set; }
        virtual public Subject Subject { get; set; }
        public string Type { get; set; }
        virtual public Teacher MainTeacher { get; set; }
        virtual public Teacher LabTeacher { get; set; }
        virtual public CourseProgram ProgramId { get; set; }
        [NotMapped]
        public string Name { get { return Subject.Name + " " + Type + " " + MainTeacher.ToShortString(); } }
    }
}

MySchedulerWork/Controllers/CourseProgramsController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulerWork.Data;
using MySchedulerWork.Models;

namespace MySchedulerWork.Controllers
{
    public class CourseProgramsController : Controller
    {
        private readonly MyAppContext _context;

        public CourseProgramsController(MyAppContext context)
        {
            _context = context;
        }

        // GET: CoursePrograms
        public async Task<IActionResult> Index()
        {
            var stream = HttpContext.Session.GetString("JwToken");
            var role = "";
            var username = "";
            if (!string.IsNullOrEmpty(stream))
            {
                var handler = new JwtSecurityTokenHandler();
                var token = handler.ReadToken(stream) as JwtSecurityToken;
                role = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
                username = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultNameClaimType).Value;
            }

            ViewBag.Username = username;
            ViewBag.Role = role;

            ViewBag.CoursePrograms = await _context.CourseProgram.ToListAsync();
            return View();
        }

        // GET: CoursePrograms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var stream = HttpContext.Session.GetString("JwToken");
            var role = "";
            var username = "";
            if (!string.IsNullOrEmpty(stream))
            {
                var handler = new JwtSecurityTokenHandler();
                var token = handler.ReadToken(stream) as JwtSecurityToken;
                role = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
                username = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultNameClaimType).Value;
            }

            ViewBag.Username = username;
            ViewBag.Role = role;

            if (id == null)
            {
                return NotFound();
            }

            var courseProgram = await _context.CourseProgram
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courseProgram == null)
            {
                return NotFound();
            }
            List<Program_Subject> ProgSubj = await _context.Program_Subjects
                .Where(p => p.ProgramId.Id == courseProgram.Id)
                .OrderBy(p => p.Subject.Name).ThenBy(p=>p.Type)
                .ToListAsync();

           /* List<ProgramToGroup> ProgGroup = await _context.ProgramToGroups
                .Where(p => p.CourseProgram.Id == courseProgram.Id)
                .ToListAsync();
           */
            ViewBag.ProgSubj = ProgSubj;
            //  ViewBag.ProgGroup = ProgGroup;

            // var GroupsToThisCourse = await _context.ProgramToGroups.Where(p => p.CourseProgram.Id == id).ToListAsync();

            ViewBag.ProgToGroup = courseProgram.Groups;

            var Groups = new SelectList( await _context.Groups.Where(g => g.CourseProgram.Id != courseProgram.Id && g.Course == courseProgram.Course).ToListAsync(),"Id","Name");
            ViewBag.Groups = Groups;

            return View(courseProgram);
        }
        [HttpPost]
        public async Task<IActionResult> CreateProgToGroup()
        {
            var stream = HttpContext.Session.GetString("JwToken");
            var role = "";
            var username = "";
            if (!string.IsNullOrEmpty(stream))
            {
                var handler = new JwtSecurityTokenHandler();
                var token = handler.ReadToken(stream) as JwtSecurityToken;
                role = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
                username = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultNameClaimType).Value;
            }

            ViewBag.Username = username;
            ViewBag.Role = role;

            int CourseId = Convert.ToInt32(Request.Form["courseid"]);
            if (Request.Form["groupid"] != "")
            {
                int groupid = Convert.ToInt32(Request.Form["groupid"]);
                CourseProgram courseprog = _context.CourseProgram.First(p => p.Id == CourseId);
                Group group = _context.Groups.First(p => p.Id == groupid);
                group.CourseProgram = courseprog;
                _context.Update(group);
                await _context.SaveChangesAsync();
                /*if (await _context.ProgramToGroups.FirstOrDefaultAsync(p => p.CourseProgram.Id == CourseId && p.Group.Id == groupid) == null)
                {
                    ProgramToGroup programToGroup = new ProgramToGroup();
                    programToGroup.CourseProgram = _context.CourseProgram.First(p => p.Id == CourseId);
                    programToGroup.Group = _context.Groups.First(p => p.Id == groupid);
                    _context.Add(programToGroup);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", new { id = CourseId });
                }*/
            }
            return RedirectToAction("Details",new { id = CourseId });
        }
        [HttpPost]
        public async Task<IActionResult> DeleteProgrameToGroup()
        {
            var stream = HttpContext.Session.GetString("JwToken");
            var role = "";
            var username = "";
            if (!string.IsNullOrEmpty(stream))
            {
                var handler = new JwtSecurityTokenHandler();
                var token = handler.ReadToken(stream) as JwtSecurityToken;
                role = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
                username = token.Claims.First(claim => claim.Type == ClaimsIdentity.DefaultNameClaimType).Value;
            }

            ViewBag.Username = username;
            ViewBag.Role = role;

            int id =Convert.ToInt32(Request.Form["idGr"]);
            int returnid = Convert.ToInt32(Request.Form["returnid"]); ;
            /*var programToGroup = await _context.ProgramToGroups
                .FirstOrDefaultAsync(m => m.Id == id);*/
            Group group = _context.Groups.FirstOrDefault(p => p.Id == id);
            CourseProgram course = _context.CourseProgram.FirstOrDefault(p => p.Id == returnid);
            if (group == null)
            {
                return NotFound();
            }
           

            Group Groupfordelete=  course.Groups.Find(p => p.Id == id);
            course.Groups.Remove(Groupfordelete);
            _context.Update(course);

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = returnid });
        }

        // GET: CoursePrograms/Create
        public IActionResult Create(ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            return View();
        }

        // POST: CoursePrograms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Course")] CourseProgram courseProgram)
        {
            if (ModelState.IsValid)
            {
                var element = _context.CourseProgram.FirstOrDefault(g => g.Name == courseProgram.Name);
                if (element != null)
                {
                    return Create(new ErrorViewModel()
                    {
                        ErrorMessage = "This Program already exists"
                    });
                }
                _context.Add(courseProgram);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(courseProgram);
        }

        // GET: CoursePrograms/Edit/5
        public async Task<IActionResult> Edit(int? id, ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            if (id == null)
            {
                return NotFound();
            }

            var courseProgram = await _context.CourseProgram.FindAsync(id);
            if (courseProgram == null)
            {
                return NotFound();
            }
            return View(courseProgram);
        }

        // POST: CoursePrograms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Course")] CourseProgram courseProgram)
        {
            if (id != courseProgram.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var element = _context.CourseProgram.FirstOrDefault(g => g.Name == courseProgram.Name);
                if (element != null)
                {
                    return Create(new ErrorViewModel()
                    {
                        ErrorMessage = "This Program already exists"
                    });
                }
                try
                {
                    _context.Update(courseProgram);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseProgramExists(courseProgram.Id))
                    {
                        return NotFound();
                    }
                    else

MySchedulerWork/Views/Program_Subject/Create.cshtml
@model MySchedulerWork.Models.Program_Subject

@{
    ViewData["Title"] = "Create";
    var model = ViewBag.Error;


    var error = "";


    if (model != null)
    {

        error = model.ErrorMessage;
    }
}

<h1>Додати предмет до програми</h1>


<hr />
<div class="border container" style="padding: 30px; border: 2px solid #adafae !important ">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group hidden">
                <input name="courseId" class="form-control" type="text" value="@ViewBag.CourseId" />
            </div>
            <div class="form-group">
                <label class="control-label">Предмет</label>
                @Html.DropDownList("subjectId", ViewBag.Subjects as SelectList, "Виберіть предмет", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Тип</label>
                <select id="type" class="form-control" name="type">
                    <option value="">Виберіть тип</option>
                    <option value="Лекція">Лекція</option>
                    <option value="Практика">Практика</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Викладач</label>
                @Html.DropDownList("mainteacherId", ViewBag.Teachers as SelectList, "Виберіть викладача", new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label class="control-label">Асистент</label>
                @Html.DropDownList("labteacherId", ViewBag.Teachers as SelectList, "Виберіть асистента", new { @class = "form-control" })
            </div>

            <span class="text-danger">@error</span>

            <div class="form-group" style="margin-top: 15px;">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @*//CoursePrograms/Details/1*@
    <a asp-action="Details" asp-controller="CoursePrograms" asp-route-id="@ViewBag.CourseId" class="btn btn-secondary">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MySchedulerWork/Views/Program_Subject/Delete.cshtml
@model MySchedulerWork.Models.Program_Subject

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалити</h1>


<div class="border container" style="padding: 30px; border: 2px solid #adafae !important ">
    @*<div class="form-group hidden">
            <input name="courseId" class="form-control" type="text" value="@ViewBag.CourseId" />
        </div>*@
    <h4>Program_Subject</h4>
    <hr />
    <div class="form-group row">
        <div class="col-3">
            <label asp-for="Subject"></label>
        </div>
        <div class="col-6">
            @Html.DisplayFor(model => model.Subject.Name)
        </div>
    </div>
    <div class="form-group row">
        <div class="col-3">
            <label asp-for="Type"></label>
        </div>
        <div class="col-6">
            @Html.DisplayFor(model => model.Type)
        </div>
    </div>
    <div class="form-group row">
        <div class="col-3">
            <label asp-for="MainTeacher"></label>
        </div>
        <div class="col-6">
            @Html.DisplayFor(model => model.MainTeacher.FullName)
        </div>
    </div>


    <form asp-action="Delete">
        <div class="form-group hidden">
            <input name="courseId" class="form-control" type="text" value="@ViewBag.CourseId" />
        </div>
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" />
        <a asp-controller="CoursePrograms" asp-action="Details" asp-route-id="@ViewBag.CourseId" class="btn btn-secondary">Назад</a>
    </form>
    @*<div>

        <form asp-controller="CoursePrograms" asp-action="Details" asp-route-id="@ViewBag.CourseId">
            <div class="form-group">
                <input type="submit" value="Return" class="btn btn-secondary" />
            </div>
        </form>
    </div>*@
</div>

MySchedulerWork/Views/Program_Subject/Details.cshtml
@model MySchedulerWork.Models.Program_Subject

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Program_Subject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MySchedulerWork/Views/Program_Subject/Edit.cshtml
@model MySchedulerWork.Models.Program_Subject

@{
    ViewData["Title"] = "Edit";
    var model = ViewBag.Error;


    var error = "";


    if (model != null)
    {

        error = model.ErrorMessage;
    }
}


<h1>Редагувати</h1>


<hr />
<div class="border container" style="padding: 30px; border: 2px solid #adafae !important ">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group hidden">
                <input name="courseId" class="form-control" type="text" value="@ViewBag.CourseId" />
            </div>
            <div class="form-group">
                <label class="control-label">Предмет</label>
                @Html.DropDownList("subjectId", ViewBag.Subjects as SelectList, "Виберіть предмет", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Тип</label>
                <input asp-for="Type" name="type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Викладач</label>
                @Html.DropDownList("mainteacherId", ViewBag.Teachers as SelectList, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label class="control-label">Асистент</label>
                @Html.DropDownList("labteacherId", ViewBag.LabTeachers as SelectList, "Виберіть асистента", new { @class = "form-control" })
            </div>
            <span class="text-danger">@error</span>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>

    <form asp-controller="CoursePrograms" asp-action="Details" asp-route-id="@ViewBag.CourseId">
        <div class="form-group">
            <input type="submit" value="Return" class="btn btn-secondary" />
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MySchedulerWork/Views/Program_Subject/Index.cshtml
@model IEnumerable<MySchedulerWork.Models.Program_Subject>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>