MySchedulerWork/Controllers/PairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulerWork.Data;
using MySchedulerWork.Models;

namespace MySchedulerWork.Controllers
{
    class ForEveryWeek
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ForEveryWeek(int _Id, string _Name)
        {
            Id = _Id;
            Name = _Name;
        }
    }
    public class PairsController : Controller
    {
        private readonly MyAppContext _context;

        public PairsController(MyAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Pairs.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pair = await _context.Pairs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pair == null)
            {
                return NotFound();
            }

            return View(pair);
        }

        public IActionResult Create(int groupId, int day, int number, string returnGroup, int IsEveryWeek = 0)
        {
            Group group = _context.Groups.FirstOrDefault(p => p.Id == groupId);
            if (group.CourseProgram != null)
            {
                ////////// Помилка
            }
            List<Audience> audiences = _context.Audiences.ToList();
            ViewBag.Audiences = new SelectList(audiences, "Id", "Name");

            //ViewBag.Days = new SelectList( new string[] { "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця" });

            List<Program_Subject> program_Subj = _context.Program_Subjects.Where(p => p.ProgramId.Id == group.CourseProgram.Id).ToList();
            List<PairToFGroup> PairToThatGroup = _context.PairToFGroup.Where(p => p.Group.Id == groupId).ToList();

            //program_Subj.RemoveAll(p => PairToThatGroup.FirstOrDefault(p1 => p1.Pair.Program_Subject.Id == p.Id && p1.Pair.IsEverWeek == 0) != null);

            List<ForEveryWeek> ForEveryWeekArr = new List<ForEveryWeek>();
            if (IsEveryWeek == 0)
            {
                ForEveryWeekArr.Add(new ForEveryWeek(0, "Кожного тижня"));
                ForEveryWeekArr.Add(new ForEveryWeek(1, "По чисельнику"));
                ForEveryWeekArr.Add(new ForEveryWeek(2, "По знаменнику"));
            }
            if (IsEveryWeek == 2)
            {
                ForEveryWeekArr.Add(new ForEveryWeek(2, "По знаменнику"));
            }
            if (IsEveryWeek == 1)
            {
                ForEveryWeekArr.Add(new ForEveryWeek(1, "По чисельнику"));
            }
            ViewBag.ForEveryWeek = new SelectList(ForEveryWeekArr, "Id", "Name");

            ViewBag.Subjects = new SelectList(program_Subj, "Id", "Name");
            ViewBag.Day = day;
            ViewBag.Number = number;
            ViewBag.GroupId = groupId;
            ViewBag.GroupToSend = returnGroup;
            var GroupsToCourse = _context.Groups.Where(p => p.CourseProgram.Id == group.CourseProgram.Id).ToArray();
            ViewBag.GroupList = new MultiSelectList(GroupsToCourse, "Id", "Name", new int[]{groupId});
            ViewBag.Group = groupId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create()
        {
            Pair pair = new Pair();
            int subjId = Convert.ToInt32(Request.Form["subject"]);
            int AudId = Convert.ToInt32(Request.Form["audience"]);
            int GroupId = Convert.ToInt32(Request.Form["group"]);
            int NumberId = Convert.ToInt32(Request.Form["number"]);
            int DayId = Convert.ToInt32(Request.Form["day"]);
            int IsEveryWeek = Convert.ToInt32(Request.Form["iseveryweek"]);

            string str = Request.Form["chosengroup"];
            string[] strgroupsId = str.Split(',');
            int[] groupsId = new int[strgroupsId.Length];
            for (int i = 0; i < strgroupsId.Length; i++)
            {
                groupsId[i] = Convert.ToInt32(strgroupsId[i]);
            }

            string sendedgroups = Request.Form["sendedgroups"];

            pair.Day = (DayOfWeek)DayId;
            pair.Program_Subject = await _context.Program_Subjects.FirstAsync(p => p.Id == subjId);
            pair.Audience = await _context.Audiences.FirstAsync(p => p.Id == AudId);
            pair.Number = NumberId;
            pair.IsEverWeek = IsEveryWeek;
            _context.Add(pair);
            await _context.SaveChangesAsync();
            for (int i = 0; i < groupsId.Length; i++)
            {
                PairToFGroup toGroup = new PairToFGroup();
                toGroup.Pair = pair;
                toGroup.Group = await _context.Groups.FirstAsync(p => p.Id == groupsId[i]);
                _context.Add(toGroup);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("MoveToCreator", "Scheduler", new { sendedgroups = sendedgroups });


        }

        public async Task<IActionResult> Edit(int id, int groupId, int day, int number, string returnGroup, int IsEveryWeek = 0)
        {


            var pair = await _context.Pairs.FindAsync(id);
            ViewBag.PairId = id;
            Group group = _context.Groups.FirstOrDefault(p => p.Id == groupId);
            if (group.CourseProgram != null)
            {
                ////////// Помилка
            }
            List<Audience> audiences = _context.Audiences.ToList();
            ViewBag.Audiences = new SelectList(audiences, "Id", "Name", pair.Audience.Id);

            //ViewBag.Days = new SelectList( new string[] { "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця" });

            List<Program_Subject> program_Subj = _context.Program_Subjects.Where(p => p.ProgramId.Id == group.CourseProgram.Id).ToList();
            List<PairToFGroup> PairToThatGroup = _context.PairToFGroup.Where(p => p.Group.Id == groupId).ToList();


            //program_Subj.RemoveAll(p => p.Id != pair.Program_Subject.Id && (PairToThatGroup.FirstOrDefault(p1 => p1.Pair.Program_Subject.Id == p.Id) != null)); 



            ViewBag.IsEveryWeek = IsEveryWeek;




            ViewBag.Subjects = new SelectList(program_Subj, "Id", "Name", pair.Program_Subject.Id);
            ViewBag.Day = day;
            ViewBag.Number = number;
            ViewBag.GroupId = groupId;
            ViewBag.GroupToSend = returnGroup;

            if (pair == null)
            {
                return NotFound();
            }
            return View(pair);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit()
        {
            int pairId = Convert.ToInt32(Request.Form["pairid"]);
            Pair pair = _context.Pairs.FirstOrDefault(p => p.Id == pairId);
            int subjId = Convert.ToInt32(Request.Form["subject"]);
            int AudId = Convert.ToInt32(Request.Form["audience"]);
            int GroupId = Convert.ToInt32(Request.Form["group"]);
            int NumberId = Convert.ToInt32(Request.Form["number"]);
            int DayId = Convert.ToInt32(Request.Form["day"]);
            int IsEveryWeek = Convert.ToInt32(Request.Form["iseveryweek"]);
            string sendedgroups = Request.Form["sendedgroups"];

            //pair.Day = (DayOfWeek)DayId;
            pair.Program_Subject = await _context.Program_Subjects.FirstAsync(p => p.Id == subjId);
            pair.Audience = await _context.Audiences.FirstAsync(p => p.Id == AudId);
          //  pair.Number = NumberId;
           // pair.IsEverWeek = IsEveryWeek;



            try
            {
                _context.Update(pair);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PairExists(pair.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }
            return RedirectToAction("MoveToCreator", "Scheduler", new { sendedgroups = sendedgroups });
        }
        public async Task<IActionResult> Delete(int id, string returnGroup)
        {
            var pair = await _context.Pairs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pair != null)
            {
               List< PairToFGroup> pairTo = pair.PairToFGroups;
                for(int i=0;i< pairTo.Count;i++)
                {
                    _context.Remove(pairTo[i]);
                }
                _context.Remove(pair);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("MoveToCreator", "Scheduler", new { sendedgroups = returnGroup });
        }

        // POST: Pairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pair = await _context.Pairs.FindAsync(id);
            _context.Pairs.Remove(pair);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PairExists(int id)
        {
            return _context.Pairs.Any(e => e.Id == id);
        }
    }
}

MySchedulerWork/Views/Scheduler/Index.cshtml
@{
    ViewData["Title"] = "Index";

    var error = "";

    if(ViewBag.Error != null)
    {
        error = ViewBag.Error;
    }
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="MoveToCreator">
            <!-- <div asp-validation-summary="ModelOnly" class="text-danger"></div>-->
            <div class="form-group">
                <label class="control-label">Виберіть програму</label>
                @Html.DropDownList("programid", ViewBag.ProgramList as SelectList, "Виберіть курс", new { @class = "form-control", @onChange = "changeGroup()" })
                <!--<span asp-validation-for="Name" class="text-danger"></span>-->
            </div>
            <div class="form-group">
                <label class="control-label">Виберіть групи</label>
                @Html.ListBox("groups", ViewBag.GroupList as MultiSelectList, new { @class = "form-control" })
            </div>
            <span class="text-danger">@error</span>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MySchedulerWork/Views/Scheduler/OpenCreator.cshtml
@using MySchedulerWork.Controllers;
@{
    ViewData["Title"] = "Index";
}

<h1>Create</h1>
<label>@ViewBag.CourseId</label>
<div class="container">
    <div class="text-center" style="margin-bottom: 15px">
        <a href="@Url.Action("ExportToCSV", "Scheduler")" class="btn btn-primary" >Експортувати в CSV</a>
    </div>
    <div class="row align-items-start">
        <div class="col-sm-1 border"></div>
        @{
            List<Group> groups = ViewBag.Groups as List<Group>;
            Dictionary<string, List<Pair>> dict = ViewBag.dict as Dictionary<string, List<Pair>>;
            List<HasConflict> conf = ViewBag.Conflict;
            @for (int i = 0; i < groups.Count; i++)
            {
                <div class="col border">@groups[i].Name</div>
            }

        }
    </div>
    @{
        for (int i = 0; i < 5; i++)
        {
            <div class="row">
                <div class="col-sm-12 text-center border border-dark">
                    @ViewBag.Days[i]
                </div>
            </div>
            for (int j = 0; j < 8; j++)
            {
                <div class="row align-items-start">
                    <div class="col-sm-1 border blockpair">@ViewBag.TimeOfPairs[j]</div>


                    @for (int k = 0; k < groups.Count; k++)
                    {
                        string key = @groups[k].Name;
                        //Pair curPair = dict[key].FirstOrDefault(p => (int)p.Day == i && p.Number == j);
                        var curPairs = dict[key].Where(p => (int)p.Day == i && p.Number == j).OrderBy(p => p.IsEverWeek).ToList();
                        if (curPairs.Count == 0)
                        {
                            <div class="col border blockpair">
                                @Html.ActionLink("Додати", "Create", "Pairs", new { groupId = groups[k].Id, day = i, number = j, returnGroup = ViewBag.GroupToSend }, htmlAttributes: new { @class = "btn btn-success" })
                            </div>
                        }
                        else
                        {
                            if (curPairs.Count == 1)
                            {
                                HasConflict ifConf = conf.FirstOrDefault(p => p.Pair.Id == curPairs[0].Id);
                                if (ifConf == null)
                                {
                                    <div class="col border blockpair" style="padding:0">
                                        @if (curPairs[0].IsEverWeek == 0)
                                        {
                                            <div>@curPairs[0].Program_Subject.Subject.Name</div>
                                        }
                                        else
                                        {
                                            if (curPairs[0].IsEverWeek == 1)
                                            {
                                                <div class="blockpair-short border">@curPairs[0].Program_Subject.Subject.Name</div>
                                                <div class="blockpair-short"></div>
                                            }
                                            else
                                            {
                                                <div class="blockpair-short border"></div>
                                                <div class="blockpair-short">@curPairs[0].Program_Subject.Subject.Name</div>
                                            }
                                        }
                                    </div>
                                }
                                else
                                {

                                    @if (curPairs[0].IsEverWeek == 0)
                                    {
                                        <div class="col border blockpair conflict">
                                            @curPairs[0].Program_Subject.Subject.Name
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="col border blockpair" style="padding:0">
                                            @if (curPairs[0].IsEverWeek == 1)
                                            {
                                                <div class="blockpair-short conflict border">@curPairs[0].Program_Subject.Subject.Name</div>
                                                <div class="blockpair-short"></div>
                                            }
                                            else
                                            {
                                                <div class="blockpair-short border"></div>
                                                <div class="blockpair-short conflict">@curPairs[0].Program_Subject.Subject.Name</div>
                                            }
                                        </div>
                                    }
                                }
                            }
                            else
                            {
                                HasConflict ifConf1 = conf.FirstOrDefault(p => p.Pair.Id == curPairs[0].Id);
                                HasConflict ifConf2 = conf.FirstOrDefault(p => p.Pair.Id == curPairs[1].Id);
                                <div class="col border blockpair">
                                    @if (ifConf1 == null)
                                    {
                                        <div class="blockpair-short border">@curPairs[0].Program_Subject.Subject.Name</div>
                                    }
                                    else
                                    {
                                        <div class="blockpair-short conflict border">@curPairs[0].Program_Subject.Subject.Name</div>
                                    }
                                    @if (ifConf2 == null)
                                    {
                                        <div class="blockpair-short">@curPairs[1].Program_Subject.Subject.Name</div>
                                    }
                                    else
                                    {
                                        <div class="blockpair-short conflict">@curPairs[1].Program_Subject.Subject.Name</div>
                                    }
                                </div>
                            }
                        }
                    }
                </div>
            }

        }
    }
</div>

<h4>Group</h4>