MySchedulerWork/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulerWork.Data;
using MySchedulerWork.Models;

namespace MySchedulerWork.Controllers
{
    public class GroupsController : Controller
    {
        private readonly MyAppContext _context;

        public GroupsController(MyAppContext context)
        {
            _context = context;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            return View(await _context.Groups.ToListAsync());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Groups/Create
        public IActionResult Create(ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Course,AmountOfStudents")] Group @group)
        {
            if (ModelState.IsValid)
            {
                var element = _context.Groups.FirstOrDefault(g => g.Name == @group.Name);
                if (element != null)
                {
                    return Create(new ErrorViewModel() 
                    { 
                      ErrorMessage = "This group already exists"
                    });
                }

                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index","Home");
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id, ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            if (id == null)
            {
                return NotFound();
            }
            
            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Course,AmountOfStudents")] Group @group)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var element = _context.Groups.FirstOrDefault(g => g.Name == @group.Name);
                if (element != null)
                {
                    return await Edit(id, new ErrorViewModel()
                    {
                        ErrorMessage = "This group already exists"
                    });
                }
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var group = await _context.Groups.FindAsync(id);

            if (group.CourseProgram != null)
            {
                var course = await _context.CourseProgram.FirstOrDefaultAsync(c => c.Id == group.CourseProgram.Id);
                course.Groups.Remove(group);
                group.CourseProgram = null;
            }

            _context.Groups.Remove(group);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var @group = await _context.Groups.FirstOrDefaultAsync(u => u.Id == id);
            if (@group == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.Id == id);
        }
    }
}

MySchedulerWork/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulerWork.Data;
using MySchedulerWork.Models;

namespace MySchedulerWork.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly MyAppContext _context;

        public SubjectsController(MyAppContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Subjects.ToListAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create(ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Course")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                var element = _context.Subjects.FirstOrDefault(g => g.Name == subject.Name && g.Course == subject.Course);
                if (element != null)
                {
                    return Create(new ErrorViewModel()
                    { 
                        ErrorMessage = "This Subject already exists"
                    });
                }
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id, ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Course")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var element = _context.Subjects.FirstOrDefault(g => g.Name == subject.Name && g.Course == subject.Course);
                if (element != null)
                {
                    return await Edit(id, new ErrorViewModel()
                    {
                        ErrorMessage = "This Subject already exists"
                    });
                }
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subjects.FindAsync(id);
            _context.Subjects.Remove(subject);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool SubjectExists(int id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }
    }
}

MySchedulerWork/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulerWork.Data;
using MySchedulerWork.Models;

namespace MySchedulerWork.Controllers
{
    public class TeachersController : Controller
    {
        private readonly MyAppContext _context;

        public TeachersController(MyAppContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Teachers.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create(ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LastName,Name,FutherName")] Teacher teacher)
        {
            //if (ModelState.IsValid)
            //{
            //    _context.Add(teacher);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction("Index", "Home");
            //}
            //return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                var element = _context.Teachers.FirstOrDefault(g => g.Name == teacher.Name &&
                                                               g.LastName == teacher.LastName &&
                                                               g.FutherName == teacher.FutherName);
                if (element != null)
                {
                    return Create(new ErrorViewModel()
                    {
                        ErrorMessage = "This Teacher already exists"
                    });
                }

                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id, ErrorViewModel error = null)
        {
            ViewBag.Error = error;
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LastName,Name,FutherName")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var element = _context.Teachers.FirstOrDefault(g => g.Name == teacher.Name &&
                                                               g.LastName == teacher.LastName &&
                                                               g.FutherName == teacher.FutherName);
                if (element != null)
                {
                    return Create(new ErrorViewModel()
                    {
                        ErrorMessage = "This Teacher already exists"
                    });
                }
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.FindAsync(id);
            _context.Teachers.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool TeacherExists(int id)
        {
            return _context.Teachers.Any(e => e.Id == id);
        }
    }
}

MySchedulerWork/Views/Home/AdminsInfoPAGE.cshtml
@{
    ViewData["Title"] = "View";
}

<!DOCTYPE html>
<html>
<head>
    <title>Вітаємо</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            margin: 0;
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-top: 50px;
        }

        h2 {
            color: #333;
            text-align: center;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <h1>Ласкаво просимо на наш сайт складання розкладу!</h1>
    <h2>
        Тут ви знайдете зручні інструменти для створення та перегляду розкладу занять.
        Наш сайт допоможе вам організувати навчальний процес, забезпечити правильне розподілення викладачів, аудиторій
        і предметів. Завдяки нашим функціям, ви зможете ефективно керувати навчальними програмами і
        забезпечити відповідність груп і предметів, які ці групи вивчають.
    </h2>
    <h1>
        Домашня сторінка:
    </h1>
    <h2>
        На цій сторінці ви знайдете вітання і короткий опис нашого сайту.
    </h2>
       
    <h1>
        Списки
    </h1>
    <h2>
        Сторінка зі списками груп викладачів, аудиторій і предметів:
        Тут ви зможете переглянути і керувати списками груп викладачів, 
        аудиторій і предметів. Додавайте нові записи, видаляйте або редагуйте
        існуючі дані для забезпечення актуальності вашої бази даних.
    </h2>
    <h1>
        Навчальні програми
    </h1>
    <h2>
        На цій сторінці ви зможете переглянути список навчальних програм і відповідні групи, 
        які вивчаються в кожній програмі. Це допоможе вам краще організувати розподіл предметів для груп та забезпечити їх консистентність.
    </h2>
    <h1>
        Розклад
    </h1>
    <h2>
        На цій сторінці ви зможете задати свою групу, або список груп і переглянути розклад занять спеціально для неї. Ви отримаєте повну інформацію про час, 
        місце проведення та предмети, що вивчаються в певний день або тиждень. Зручний і простий у використанні інтерфейс дозволить вам швидко знайти необхідну інформацію.
        Як Адміністратор у вас буде додаткова можливість додавати або забирати пари.
    </h2>
</body>
</html>

MySchedulerWork/Views/Home/HelloPage.cshtml
@{
    ViewData["Title"] = "View";
}

<!DOCTYPE html>
<html>
<head>
    <title>Вітаємо</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            margin: 0;
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-top: 50px;
        }
    </style>
</head>
<body>
    <h1>Вітаємо вас на сайті для складання розкладу для викладачів та студентів Національного Львівського університету ім. Івана Франка.</h1>
    <h1>Факультету Прикладної Математики та Інформатики</h1>
    <h1>Це проект написаний і використаний як дипломна робота студента 4 курсу</h1>
    <h1>Для короткого ознайомлення з ф-ціоналом перейдіть на секцію Короткий Опис</h1>
</body>
</html>

MySchedulerWork/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<ul class="nav nav-pills mb-4" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-audience" type="button" role="tab" aria-controls="pills-audience" aria-selected="false">Аудиторії</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Викладачі</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Групи</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Предмети</button>
    </li>


</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <a asp-action="Create" asp-controller="Groups" class="btn btn-success " style="margin-bottom: 15px">
            Створити
        </a>
        
    <div class="scrollit">
        <table class="table" style="border: 2px solid #adafae">
            <thead>
                <tr class="table-first-line">
                    <th scope="col">
                        Назва
                    </th>
                    <th scope="col">
                        Курс
                    </th>
                    <th scope="col">
                        К-сть студентів
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Groups)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Course
                        </td>
                        <td>
                            @item.AmountOfStudents
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="Groups" asp-route-id="@item.Id" class="btn btn-primary">Редагувати</a>
                            <a asp-action="Delete" asp-controller="Groups" asp-route-id="@item.Id" class="btn btn-danger">Видалити</a>

                            @*<a asp-action="Details" asp-route-id="@item.Id">Details</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                            @* @Html.ActionLink("Редагувати", "Edit", "Groups", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                            @Html.ActionLink("Видалити", "Delete", "Groups", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-danger" }) *@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <a asp-action="Create" asp-controller="Teachers" class="btn btn-success " style="margin-bottom: 15px">
            Створити
        </a>
        @*<p>
            @Html.ActionLink("Створити", "Create", "Teachers", new { }, htmlAttributes: new { @class = "btn btn-success" })

        </p>*@
    <div class="scrollit">
        <table class="table" style="border: 2px solid #adafae">
            <thead>
                <tr class="table-first-line">
                    <th scope="col">
                        Прізвище
                    </th>
                    <th scope="col">
                        Ім'я
                    </th>
                    <th scope="col">
                        По-Батькові
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Teachers)
                {
                    <tr>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.FutherName
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="Teachers" asp-route-id="@item.Id" class="btn btn-primary">Редагувати</a>
                            <a asp-action="Delete" asp-controller="Teachers" asp-route-id="@item.Id" class="btn btn-danger">Видалити</a>
                            <!-- <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>-->
                           @* @Html.ActionLink("Редагувати", "Edit", "Teachers", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                            @Html.ActionLink("Видалити", "Delete", "Teachers", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-danger" }) *@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    </div>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
        <a asp-action="Create" asp-controller="Subjects" class="btn btn-success " style="margin-bottom: 15px">
            Створити
        </a>
        @*<p>
            @Html.ActionLink("Створити", "Create", "Subjects", new { }, htmlAttributes: new { @class = "btn btn-success" })

        </p>*@
        <div class="scrollit">
            <table class="table" style="border: 2px solid #adafae">
                <thead>
                    <tr class="table-first-line">
                        <th scope="col">
                            Назва
                        </th>
                        <th scope="col">
                            Курс
                        </th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Subjects)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Course
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Subjects" asp-route-id="@item.Id" class="btn btn-primary">Редагувати</a>
                                <a asp-action="Delete" asp-controller="Subjects" asp-route-id="@item.Id" class="btn btn-danger">Видалити</a>
                                <!-- <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>-->
                                @*    @Html.ActionLink("Редагувати", "Edit", "Subjects", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                                @Html.ActionLink("Видалити", "Delete", "Subjects", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-danger" })*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    <div class="tab-pane fade" id="pills-audience" role="tabpanel" aria-labelledby="pills-audience-tab">
        <a asp-action="Create" asp-controller="Audiences" class="btn btn-success " style="margin-bottom: 15px">
            Створити
        </a>
        @*<p>
            @Html.ActionLink("Створити", "Create", "Audiences", new { }, htmlAttributes: new { @class = "btn btn-success" })

        </p>*@
        <div class="scrollit">
            <table class="table" style="border: 2px solid #adafae">
                <thead>
                    <tr class="table-first-line">
                        <th scope="col">
                            Назва
                        </th>
                        <th scope="col">
                            Вмістимість
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Audiences)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Capacity
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Audiences" asp-route-id="@item.Id" class="btn btn-primary">Редагувати</a>
                                <a asp-action="Delete" asp-controller="Audiences" asp-route-id="@item.Id" class="btn btn-danger">Видалити</a>

                                <!-- <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>-->
                                @*     @Html.ActionLink("Редагувати", "Edit", "Audiences", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                                @Html.ActionLink("Видалити", "Delete", "Audiences", new { id = @item.Id }, htmlAttributes: new { @class = "btn btn-danger" }) *@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            </div>
        </div>

    </div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}